-- Run this in Supabase SQL Editor.
-- This creates the table used by the GitHub Pages feedback panel.

create table if not exists public.client_recommendations (
  id bigint generated by default as identity primary key,
  section text not null,
  comment text not null,
  name text null,
  created_at timestamptz not null default now(),
  constraint client_recommendations_section_length check (char_length(section) between 1 and 150),
  constraint client_recommendations_comment_length check (char_length(comment) between 1 and 5000),
  constraint client_recommendations_name_length check (name is null or char_length(name) <= 100)
);

alter table public.client_recommendations enable row level security;

-- Make sure the API roles can use this table.
grant usage on schema public to anon, authenticated;
grant select, insert on table public.client_recommendations to anon, authenticated;

-- The website is public, so anonymous visitors can submit and view
-- recommendations. Authenticated users are also allowed.
-- NEVER expose a service_role/secret key in index.html.

drop policy if exists "Public can view client recommendations" on public.client_recommendations;
drop policy if exists "Public can submit client recommendations" on public.client_recommendations;
drop policy if exists "Anyone can view client recommendations" on public.client_recommendations;
drop policy if exists "Anyone can submit client recommendations" on public.client_recommendations;

create policy "Anyone can view client recommendations"
on public.client_recommendations
for select
to anon, authenticated
using (true);

create policy "Anyone can submit client recommendations"
on public.client_recommendations
for insert
to anon, authenticated
with check (
  char_length(trim(section)) between 1 and 150
  and char_length(trim(comment)) between 1 and 5000
  and (name is null or char_length(name) <= 100)
);

-- Optional index for newest-first display.
create index if not exists client_recommendations_created_at_idx
on public.client_recommendations (created_at desc);
